version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.12

    commands:
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - pytest

  build:
    commands:
      - docker build -t africa-agent .
      - docker tag africa-agent:latest $ECR_URI:latest

  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - docker push $ECR_URI:latest

artifacts:
  files:
    - '**/*'